-- AlterTable
ALTER TABLE "users" ALTER COLUMN "fullname" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL,
ALTER COLUMN "role" DROP NOT NULL,
ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "driver_license" DROP NOT NULL;
